language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - secure: LznNYYe838cOv16TJY64feP3/PIajG+zGztL2p/TUcZLKxtCvX/XFU+QviFk42wLUugW3uOiS1TWRtBJWN7uiVOEhTta2o1SOTbS2w7of6B/zjnhxg5ixZ6TF+SOi1oZAt0TvjMko3T/LQaGToeqaQGx9vVzlpJacXk46sd1peqb8qCP0TykqlyLH2AVUJ/eeLMQTzVqb5pU0uZYEK6afpWckSoLq/rAOOIbEAgyxJc27paY3cBY2cmErF8jUBLT5eabi1Ng19R/meQKmCOoePEJoratwDsTB6woUSI9xbIGXbjxWxC0ffPjtLAiP4HRf1RmEv+0iU4WhtZYlQbLbkGG6GVQbfUokx7c58wSSiOZol37KZ4cwVadwaJKw33Xs6muyPjsIk1PZnttO2ylddXW8TWxo2hgJ7iRO21hOQbLSH6bow66ARcIyTVDQzB7IAjnp2kJ3qjtlYy2qkMab8G3MW4qpr9Y7q1Zr8XryQc77MSYqLNL9FsK58GI+jcoms99i+GmhugjVCAaSs5LX54tEhIfZff1t49gp3xnxuHyDWErKFnodpcWNu/LTrH8GLAmOBPX9kJNpCefBAB8k+T5zZjUV6E1m/yojgmE8oX7CMF3H1KB+uL4Wb84N/Fq5d8CBvROhrrn8AokQyulS6cLC3Ij8OhMPB0P62d3x+0=
  - DJANGO_VERSION=1.11.5

services:
  - db.sqlite3

before_script:
  - python propalyzer_site/manage.py makemigrations
  - python propalyzer_site/manage.py migrate
  
# command to run tests
script:
  - python propalyzer_site/manage.py test
  
# safelist
branches:
  only:
  - ci-test
